services:
  mkdocs:
    image: python:3.12-slim
    working_dir: /work
    volumes:
      - .:/work
    ports:
      - "8000:8000"
    command: sh -c "pip install mkdocs-material && mkdocs serve -a 0.0.0.0:8000"